### ISSUE TITLE
Sample tests should surface error messages

### ISSUE THREAD

**Issue by kweinmeister** [googleapis/java-retail#367]
There are tests with assertions that don't provide a message. This makes debugging difficult, because you can't see directly from the Github issue what the problem is. You have to navigate into the source code.

Tests should be updated to include the message along with the condition.

For example, here's a test failure that just showed up as an AssertionError:

```
[ERROR] init.CreateTestResourcesTest.testCreateTestResources  Time elapsed: 11.89 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
        ...
        at init.CreateTestResourcesTest.testCreateTestResources(CreateTestResourcesTest.java:46)
```
By looking at the source code, I see the problem is this line:
```
Assert.assertTrue(output.matches("(?s)^(.*Import products operation is completed.*)$"));
```

So, this line could be updated to:
```
Assert.assertTrue("Import products operation is completed", output.matches("(?s)^(.*Import products operation is completed.*)$"));
```

**Comment by sborisenkox** [comment]
I have changed all the tests with another logic (more readable) after I got code review comments.
E.g. https://github.com/googleapis/java-retail/blob/b2a435a581f2d32803e65ee67eb3c1693a97b5d5/samples/interactive-tutorials/src/test/java/init/CreateTestResourcesTest.java

**Comment by sborisenkox** [comment]
It's resolved.
If you accept it, could you please close the issue?
