### ISSUE TITLE
Add comments to java-retail/samples/interactive-tutorials/src/main/java/events/setup/

### ISSUE THREAD

**Issue by alicejli** [googleapis/java-retail#515]
There currently are no comments in any of the files in the `java-retail/samples/interactive-tutorials/src/main/java/events/setup/` directory. It would be helpful to add comments to the files or a README into the directory to understand what these files are for. 

First highlighted in this PR: https://github.com/googleapis/java-retail/pull/494

**Comment by Shabirmean** [comment]
Closing this as part of the mono-repo migration. 
See mirror issue at: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/7429
